[tool.poetry]
name = "pythonproject123"
version = "0.1.0"
description = ""
authors = ["Danil <fofogogo12345689@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
